<a href="https://colab.research.google.com/github/ziedjouini/machine-learning/blob/main/Copie_de_dojo_Paris_20221213.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



En utilisant NumPy, affichez les informations suivantes :
- En utilisant l'attribut `shape` et du slicing, affichez **uniquement** le nombre de colonnes (et donc le nombre de courses effectuées)
- un array avec le classement obtenu par chaque cheval à la 3e course
- le nombre de fois où le cheval 1 a fait partie du top 3
- le classement le plus mauvais du cheval 2
- le classement moyen par cheval (vous pouvez utiliser l'attribut `.mean(axis = ???)` en testant le paramètre `axis`)
- le nombre de fois où chaque cheval a fait partie du top 2 (vous pouvez utiliser `np.sum(axis = ???)` en testant le paramètre `axis`)
- le pourcentage de fois où chaque cheval a fait partie du top 2
- un array de booléens indiquant si chaque cheval a fait partie du top 2 au moins 40% des courses
- en utilisant `np.where`, les index des chevaux arrivés au moins 40% des courses dans les 2 meilleurs

In [1]:
import numpy as np

courses = {
    "cheval1": [2, 2, 3, 2, 5, 4, 3, 5, 4, 1, 1, 1, 4, 4, 3, 5, 5, 3, 5, 5],
    "cheval2": [1, 1, 2, 1, 3, 1, 1, 2, 1, 4, 4, 2, 3, 1, 2, 1, 1, 4, 4, 1],
    "cheval3": [4, 4, 1, 3, 4, 2, 2, 3, 3, 3, 5, 4, 1, 5, 4, 3, 2, 1, 1, 4],
    "cheval4": [5, 3, 4, 4, 2, 3, 5, 1, 2, 5, 3, 5, 5, 3, 5, 2, 3, 5, 3, 3],
    "cheval5": [3, 5, 5, 5, 1, 5, 4, 4, 5, 2, 2, 3, 2, 2, 1, 4, 4, 2, 2, 2],
}

courses_arr = np.array(list(courses.values()))

In [2]:
courses_arr

array([[2, 2, 3, 2, 5, 4, 3, 5, 4, 1, 1, 1, 4, 4, 3, 5, 5, 3, 5, 5],
       [1, 1, 2, 1, 3, 1, 1, 2, 1, 4, 4, 2, 3, 1, 2, 1, 1, 4, 4, 1],
       [4, 4, 1, 3, 4, 2, 2, 3, 3, 3, 5, 4, 1, 5, 4, 3, 2, 1, 1, 4],
       [5, 3, 4, 4, 2, 3, 5, 1, 2, 5, 3, 5, 5, 3, 5, 2, 3, 5, 3, 3],
       [3, 5, 5, 5, 1, 5, 4, 4, 5, 2, 2, 3, 2, 2, 1, 4, 4, 2, 2, 2]])

In [4]:
courses_arr.shape

(5, 20)

In [5]:
courses_arr.shape[1]

20

In [7]:
courses_arr[:,2]

array([3, 2, 1, 4, 5])

In [11]:
sum(courses_arr[0,:]<=3)

10

In [14]:
courses_arr[1,:].max()

4

In [17]:
courses_arr[:,:].mean(axis=1)

array([3.35, 2.  , 2.95, 3.55, 3.15])

In [20]:
(courses_arr[:,:]<=2).sum(axis=1)

array([ 6, 14,  7,  4,  9])